### ISSUE TITLE
heads up: other art

### ISSUE THREAD

**Issue by colemickens** [diamondburned/nix-hash-fuzzer#1]
Hey,

I think there are other nixpkgs auto-update things that I'm not up to date on, but I found this repo and thought I'd mention---

-- I have a script in nixpkgs-wayland that does some similar thing. There's a `metadata.nix`, and it try-builds, grep-replaces hashes to auto-update a big package set to latest.

Not sure if its of any interest, especially  as its a nushell script nowadays, but thought I'd mention it: https://github.com/nix-community/nixpkgs-wayland/blob/28900cc4d5e76d8e0c3729278b4422a4fca0f06b/main.nu#L18-L97

**Comment by diamondburned** [comment]
Hi, thank you for mentioning this. I'm also aware of a few other autoupdate scripts including `nix-update` that I ended up using for one of my projects.
